### PR TITLE
Remove unused dependencies from package.json

### PR DESCRIPTION
**Pull request by KKoukiou**

### CODE REVIEW

**Comment by KKoukiou** [comment]
@jgiardino @henrywang Are these really leftovers from the past?

**Comment by KKoukiou** [comment]
looks like cjs is used by travis ci.. https://travis-ci.org/weldr/welder-web/builds/514185579?utm_source=github_status&utm_medium=notification

**Comment by jgiardino** [comment]
Thanks for making these updates! I'm not aware of any need for these dependencies.

**Comment by martinpitt** [comment]
The [Travis failure](https://travis-ci.org/weldr/welder-web/jobs/514185581) looks relevant -- perhaps `postcss` was a transitive dependency of the removed ones, and now needs to be added explicitly?

**Comment by henrywang** [comment]
> The [Travis failure](https://travis-ci.org/weldr/welder-web/jobs/514185581) looks relevant -- perhaps `postcss` was a transitive dependency of the removed ones, and now needs to be added explicitly?

Correct! `pixrem` depends on `postcss`.

**Comment by KKoukiou** [comment]
> The [Travis failure](https://travis-ci.org/weldr/welder-web/jobs/514185581) looks relevant -- perhaps `postcss` was a transitive dependency of the removed ones, and now needs to be added explicitly?

Yeah, probably. Still, since stylelint uses it, I don't get why it's not dependency of that.. I repushed with adding postcss back.

**Pull request merged**
