### PR TITLE
Compile with code coverage enabled, collect coverage result and upload result to codecov.

### PR DESCRIPTION
**Pull request by henrywang**
@martinpitt, could you please add another test in cockpit CI to run test on chrome with code coverage enabled? Thanks.
The test needs two environment variables in cockpit CI container.
1. CODECOV=true
2. CODECOV_TOKEN=<token>
Could you please add two environment variables? Thanks.

### CODE REVIEW

**Comment by martinpitt** [comment]
Passing arbitrary env variables (or more generally, run them with different scenarios) is not currently possible, so we'll need to extend Cockpit's tests-invoke a bit to generalize `$TEST_OS`. I'll look into it ASAP (but will take a few days, I'm travelling a lot).

**Comment by martinpitt** [comment]
With that you also don't need a `$CODECOV` switch -- just enable coverage if ~/.config/codecov-token exists.

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpituous/pull/210 implements the ~/.config/codecov-token secrets symlink in our tests containers. @henrywang , can you please gpg-send me the token, or put it onto some red hat server where I can get it?

**Comment by henrywang** [comment]
@martinpitt, shared token with you by google doc.

**Comment by henrywang** [comment]
> With that you also don't need a `$CODECOV` switch -- just enable coverage if ~/.config/codecov-token exists.

@martinpitt, the cockpit ci will add ~/.config/codecov automatically on chrome scenario? Thanks.

**Comment by henrywang** [comment]
@martinpitt, updated according to your comments. I'll fix failed case on chrome in another PR. Thanks.

**Pull request merged**
