### PR TITLE
Adjustments to how we start tests with lorax-composer

### PR DESCRIPTION
**Pull request by atodorov**
See https://github.com/weldr/lorax/pull/387/

### CODE REVIEW

**Comment by bcl** [comment]
This should not be needed. The lorax-composer.service has this in it to make sure the socket is always right:
    ExecStartPre=/usr/bin/systemd-tmpfiles --create /usr/lib/tmpfiles.d/lorax-composer.conf

**Comment by atodorov** [comment]
@bcl what if we start lorax-composer manually like we do in the tests ? 

I am seeing the following in the Jenkins console.log:

```
sudo lorax-composer --group cockpit-ws /recipes &
until sudo curl --unix-socket /run/weldr/api.socket http://localhost:4000/api/status | grep '"db_supported": true'; do \
    sleep 1; \
    echo "Waiting for backend API to become ready before testing ..."; \
done;
curl: (7) Failed to connect to /run/weldr/api.socket: No such file or directory
Traceback (most recent call last):
  File "/sbin/lorax-composer", line 277, in <module>
    make_yum_dirs(server.config["COMPOSER_CFG"])
  File "/usr/lib/python2.7/site-packages/pylorax/api/config.py", line 83, in make_yum_dirs
    os.makedirs(p_dir)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/var/lib/lorax/composer/repos.d'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 315, in _exit_function
    p._popen.terminate()
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 171, in terminate
    os.kill(self.pid, signal.SIGTERM)
OSError: [Errno 1] Operation not permitted
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.7/multiprocessing/util.py", line 315, in _exit_function
    p._popen.terminate()
  File "/usr/lib64/python2.7/multiprocessing/forking.py", line 171, in terminate
    os.kill(self.pid, signal.SIGTERM)
OSError: [Errno 1] Operation not permitted
```

**Comment by atodorov** [comment]
Note: as a side note, I don't think we even have systemd on the RHEL7 docker image that is used for testing so the above approach may not work.

**Comment by bcl** [comment]
Ah! Sorry, missed that you are starting it manually. Nevermind, looks fine to me if that works for you.

**Pull request merged**
