### PR TITLE
Trigger the po-refresh bot

### PR DESCRIPTION
**Pull request by mvollmer**
Depends on #403

### CODE REVIEW

**Comment by mvollmer** [comment]
Zanata creds need to be available when po-refresh runs.  I'll check our options.

**Comment by mvollmer** [comment]
> Zanata creds need to be available when po-refresh runs. I'll check our options.

Oh, cool, our bots are already a "Translation Maintainer" for welder-web.

**Comment by martinpitt** [comment]
@mvollmer: If we give "cockpit" translation privs in zanata, it should work. Indeed our bots have a zanata token already. And https://fedora.zanata.org/project/view/welder-web/people?dswid=-6732 looks like cockpit should already have access?

**Comment by mvollmer** [comment]
> I can't get make po-pull to work locally here with the token from our bots:

It does work in the pods, though.  I'll try to figure out what the difference is.

**Pull request merged**
