### PR TITLE
Add COPR build to cockpituous release script

### PR DESCRIPTION
**Pull request by martinpitt**
This will automatically upload and build new releases to our COPR
archive.

Blockers:
 - [x] Fix cockpituous' release-copr script: https://github.com/cockpit-project/cockpituous/pull/174
 - [x] Allow cockpituous to access @weldr COPR
 - [x] Allow cockpituous to access welder GitHub (requires 2FA for that user)

### CODE REVIEW

**Comment by martinpitt** [comment]
I tested this on my own fork: I tagged a 0.0.1 release on https://github.com/martinpitt/welder-web/releases, changed the COPR repo to martinpitt/welder-web, and ran

    ~/upstream/cockpituous/release/release-runner -v -r https://github.com/martinpitt/welder-web utils/cockpituous-release

This produced the [automatic GitHub release](https://github.com/martinpitt/welder-web/releases/tag/0.0.1) as well as a working [COPR build](https://copr.fedorainfracloud.org/coprs/martinpitt/welder-web/build/721722/).

**Comment by martinpitt** [comment]
I rolled out the cockpituous fix. The tokens don't need to block landing this PR, as currently the release script isn't being used by our infra yet.

**Comment by henrywang** [comment]
After discuss with @martinpitt, this PR will not be merged until the second block issue got fixed.

**Comment by martinpitt** [comment]
@henrywang : The users are now set up, i. e. cockpituous is a member of the GitHub weldr organization and the COPR cockpit user is a member of @weldr. So this should work now, and we can land this.

**Pull request merged**
