### PR TITLE
Switch to using the blueprints API instead of recipes.

### PR DESCRIPTION
**Pull request by bcl**
This requires an API server that has also made the change.

Merging this needs to be coordinated with the related PRs from lorax-composer, bdcs-api, and bdcs-cli.

### CODE REVIEW

**Comment by jgiardino** [comment]
When I review the updates, I don't see anything that was missed. But I also am not able to test this locally with the new api. I haven't been able to get the new api set up on my machine. 

Should we see if @jkozol can test this with his local build?

**Comment by jkozol** [comment]
This looks good to me. I am working on running the tests through lorax-composer. @bcl Do you have instructions on how to build and start the bdcs-api so I can run the UI tests against it?

**Comment by atodorov** [comment]
@jkozol see #215, it's currently blocked by the switch to the Haskell backend and #221 but let's keep in touch once these two are done.

**Comment by atodorov** [comment]
cherry-picked and merged as part of #225

**Pull request closed without merging**
