### PR TITLE
Add RHEL-X in welder-web test scenarios.

### PR DESCRIPTION
**Pull request by henrywang**
- [x] add nodejs to rhel-x image: https://github.com/cockpit-project/cockpit/pull/10342

### CODE REVIEW

**Comment by martinpitt** [comment]
I sent https://github.com/cockpit-project/cockpit/pull/10342 to add node.js to the rhel-x image. Let's not bring back the brittle GPG key download on every test run.

I tried to run the tests locally, and that failed with
```
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
appstream                                       137  B/s | 544  B     00:03    
baseos                                          156  B/s | 544  B     00:03    
Failed to synchronize cache for repo 'RHEL-8-NIGHTLY-AppStream', ignoring this repo.
Failed to synchronize cache for repo 'RHEL-8-NIGHTLY-BaseOS', ignoring this repo.
No match for argument: gcc-c++
Error: Unable to find a match
```
This looks like a recent change in rhel-x that subscriptions are now required? Unfortunately our cockpit team subscription does not work either, so right now I don't know how to proceed, or even build new images. I need to ask around.

So this is blocked on https://github.com/cockpit-project/cockpit/pull/10342 for now. Then the node installation code should go away again from vm.install.

**Comment by henrywang** [comment]
It's updated. Thanks @martinpitt.

**Comment by martinpitt** [comment]
https://github.com/cockpit-project/cockpit/pull/10408 will enable this for PRs, once this lands. I still want to wait for the chrome test, it's flaky.

**Comment by martinpitt** [comment]
Still [failing](https://fedorapeople.org/groups/cockpit/logs/pull-390-20181023-144747-931c7f31-cockpit-rhel-7-6-chrome/), retrying once more.

**Pull request merged**
