### PR TITLE
Check for NPM dependency updates

### PR DESCRIPTION
**Pull request by cockpituous**
Check for any outstanding update of point version of any outstanding NPM package dependency
 * [ ] FAIL: npm-update

### CODE REVIEW

**Comment by cockpituous** [comment]
Please manually check features related to these files:

```
package.json:    "@babel/polyfill": "7.4.0",
webpack.config.js:  // redux-saga uses generators, babel compiles using regenerator runtime included in @babel/polyfill
webpack.config.js:  entry: ["@babel/polyfill", "./main.js"],
```

**Comment by cockpituous** [comment]
npm-update in progress on centosci-tasks-zhbcf.
Log: https://209.132.184.41:8493/logs/npm-update-602-20190322-110505/

**Comment by cockpituous** [comment]
npm-update @babel/polyfill done: https://github.com/cockpituous/welder-web/commits/npm-update-@babel/polyfill-20190322-111414

**Comment by cockpituous** [comment]
npm-update @babel/polyfill done: https://github.com/cockpituous/welder-web/commits/npm-update-@babel/polyfill-20190322-110505

**Comment by cockpituous** [comment]
Error accessing /repos/weldr/welder-web/pulls
  Status: 422
  Reason: Unprocessable Entity
  Response: {"message":"The specified issue is already attached to a pull request.","errors":[{"value"None,"resource":"PullRequest","field":"issue","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}: https://209.132.184.41:8493/logs/npm-update-602-20190322-110505/

**Comment by martinpitt** [comment]
duplicate of #603

**Pull request closed without merging**
